name: pgbouncer

on:
  push:
    paths:
      - '.github/workflows/pgbouncer.yml'
      - 'docker_builds/pgbouncer/**'
      - '!docker_builds/pgbouncer/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgbouncer-version: [ 1.14.0 ]
    env:
      VERSION: $(cat docker_builds/pgbouncer/.version)
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.pgbouncer-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=false" \
            --build-arg PGBOUNCER_VERSION=${{ matrix.pgbouncer-version }} \
            --tag enros/pgbouncer:${{ matrix.pgbouncer-version }} \
            --file ./docker_builds/pgbouncer/Dockerfile \
            ./docker_builds/pgbouncer/
      -        
        name: Login to GitHub Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      -  
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --build-arg PGBOUNCER_VERSION=${{ matrix.pgbouncer-version }} \
            --tag enros/pgbouncer:${{ matrix.pgbouncer-version }} \
            --file ./docker_builds/pgbouncer/Dockerfile \
            ./docker_builds/pgbouncer/
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery enros/pgbouncer:${{ matrix.pgbouncer-version }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
